# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-08 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InterestingArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Coordinate')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=b'date of point')),
                ('likes', models.IntegerField(default=0)),
                ('coments', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.InstagramUser')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.City')),
                ('coordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Coordinate')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city.Coordinate'),
        ),
    ]
